//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATBAN
    {
        public int STT { get; set; }
        public int MAHD { get; set; }
        public string MABAN { get; set; }

        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> GIODATBAN { get; set; }
        public Nullable<System.DateTime> GIOTRABAN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
