//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETDATBANs = new HashSet<CHITIETDATBAN>();
            this.CHITIETDATMONANs = new HashSet<CHITIETDATMONAN>();
        }
        [DisplayName("Mã hóa đơn")]
        public int MAHD { get; set; }
        [DisplayName("Tên khách hàng")]
        public string MAKH { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TONGTIEN { get; set; }
        [DisplayName("Tình trạng")]
        public string TINHTRANG { get; set; }
        [DisplayName("Ngày lập")]
        public Nullable<System.DateTime> NGAYLAPHD { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATBAN> CHITIETDATBANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATMONAN> CHITIETDATMONANs { get; set; }
    }
}
