//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAIKHONGGIAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIKHONGGIAN()
        {
            this.BANANs = new HashSet<BANAN>();
        }
        [DisplayName("Tên không gian")]
        public int MALOAIKHONGGIAN { get; set; }
        [DisplayName("Tên không gian")]
        [Required(ErrorMessage = "Vui lòng nhập Tên không gian trước khi xác nhận!")]
        public string TENLOAIKHONGGIAN { get; set; }
        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "Vui lòng tải ảnh lên trước khi xác nhận!")]
        public string IMG { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Vui lòng nhập Mô tả trước khi xác nhận!")]
        public string MOTA { get; set; }
        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Vui lòng nhập Đơn giá trước khi xác nhận!")]
        public Nullable<decimal> DONGIA { get; set; }
        [DisplayName("Đơn vị tính")]
        [Required(ErrorMessage = "Vui lòng nhập Đơn vị tính trước khi xác nhận!")]
        public string DVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANAN> BANANs { get; set; }
    }
}
