//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.CHITIETDATMONANs = new HashSet<CHITIETDATMONAN>();
        }
    
        public int MAMONAN { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Loại món trước khi xác nhận!")]
        [DisplayName("Tên loại món")]
        public int MALOAIMON { get; set; }
        [DisplayName("Tên món")]
        [Required(ErrorMessage = "Vui lòng nhập lại Tên món trước khi xác nhận!")]
        public string TENMONAN { get; set; }
        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "Vui lòng nhập tải ảnh lên trước khi xác nhận!")]
        public string HINHANH { get; set; }
        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Vui lòng nhập Đơn giá trước khi xác nhận!")]
        public Nullable<decimal> DONGIA { get; set; }
        [DisplayName("Đơn vị tính")]
        [Required(ErrorMessage = "Vui lòng nhập Đơn vị tính trước khi xác nhận!")]
        public string DVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATMONAN> CHITIETDATMONANs { get; set; }
        public virtual LOAIMON LOAIMON { get; set; }
    }
}
